### ISSUE TITLE
Can not add multiple forms

### ISSUE THREAD

**Issue by mariam-japaridze** [nietonfir/GoogleRecaptchaBundle#6]
Hello. I have 2 forms with different fields on different pages. I want both to have recaptcha. In config.yml I can only define one form_name in validation parameters. can I add several? Thanks

**Comment by nietonfir** [comment]
That's on my ToDo list. If you want to contribute, feel free to send a PR. ;-)

I think the general idea is to allow [multiple configuration statements](http://symfony.com/doc/current/components/config/definition.html#array-nodes) for validation (like [doctrine](http://symfony.com/doc/current/doctrine/multiple_entity_managers.html)). Rendering shouldn't be so hard according to the last example in https://developers.google.com/recaptcha/docs/display#example
