### ISSUE TITLE
RECAPTCHA::__CONSTRUCT() MUST BE AN INSTANCE OF NIETONFIR\GOOGLE\RECAPTCHA\API\RESPONSEFACTORYINTERFACE, INSTANCE OF NIETONFIR\GOOGLE\RECAPTCHA\API\RESPONSE GIVEN

### ISSUE THREAD

**Issue by grekpg** [nietonfir/GoogleRecaptchaBundle#8]
i have this error 
FATALTHROWABLEERROR IN RECAPTCHA.PHP LINE 19:
TYPE ERROR: ARGUMENT 2 PASSED TO NIETONFIR\GOOGLE\RECAPTCHA\RECAPTCHA::__CONSTRUCT() MUST BE AN INSTANCE OF NIETONFIR\GOOGLE\RECAPTCHA\API\RESPONSEFACTORYINTERFACE, INSTANCE OF NIETONFIR\GOOGLE\RECAPTCHA\API\RESPONSE GIVEN

i use last version for symfony 2.X 
"nietonfir/google-recaptcha-bundle": "v0.0.3",
how to fix it ?

**Comment by nietonfir** [comment]
Add `"nietonfir/google-recaptcha": "v0.0.3"` to your composer.json and run
`composer update nietonfir/google-recaptcha`.
